### ISSUE TITLE
NH3 versus NH4

### ISSUE THREAD

**Issue by Yamerlinck** [smart-data-models/dataModel.WaterQuality#1]
Dear,

I noticed that in the description of the properties you do not make a distinction between NH3 and NH4. Both of them are described as 'Concentration of ammonium'. However there is definetly a difference between them. NH3 is ammoni**a** and NH4 is the ionized form called ammoni**um**.

Best regards,

Youri

**Comment by albertoabellagarcia** [comment]
Should we change therefore the definition for NH3, isn't it?

**Comment by Yamerlinck** [comment]
Yes, indeed

**Comment by albertoabellagarcia** [comment]
done, thanks
