### ISSUE TITLE
Wrong definition of id in the examples

### ISSUE THREAD

**Issue by flopezag** [smart-data-models/dataModel.WaterQuality#9]
I think that the id of the examples of this subject are wrong, e.g.:

  "id": "waterqualityobserved:Sevilla:D1",

It is not following the schema "urn:...."

**Comment by bobeal** [comment]
Well, the spec only requires an `id` to be an URI so `waterqualityobserved:Sevilla:D1` is valid. But the spec defines an URN namespace in A.3 and states that `It is recommended that applications use this URN namespace when applicable`. So better to use it :)

**Comment by albertoabellagarcia** [comment]
Next update of the data model will follow the recommendation. Thanks
